# Main Text
author: 'mass tourists'
name: 'veroVeneziano'
aka: '- only cash -'
title: '#veroVeneziano - only cash'
subtitle: "the Venezia's best brand"
payoff: "catch'em all"
description: "the Venezia's best brand"
locale: en_EN

# Url
baseurl: "" # the subpath of your site, e.g. /blog
url: https://masstourists.com

# Contact
twitter: masstourists
github:
facebook: masstourists
email: turism4masses@gmail.com
github_username:
facebook_username: masstourists
twitter_username: masstourists

# SEO
twitter:
  username: masstourists
  card: summary_large_image

facebook:
  app_id: 257678751707830
  publisher: 1647204168722946
  admins: 100027504092751

# Favicon
touch_icon: "https://masstourists.com/assets/img/logo/apple-touch-icon-144-precomposed.png"
favicon: "https://masstourists.com/assets/img/logo/favicon.ico"

# Build settings
markdown: kramdown
highlighter: rouge

#Paginator
#paginate: 3

#Style
sass:
  sass_dir: _sass
  style: compression

collections:
  activities:
    output: true
  services:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
