# Main Text
author: 'Mass Tourists'
name: 'Mass Tourists'
aka: 'Mass Tourists'
title: 'Mass Tourists - Content for the masses'
subtitle: 'Content for the masses'
payoff: 'Content for the masses'
description: 'Content for the masses'
locale: en_EN

# Url
baseurl: "" # the subpath of your site, e.g. /blog
url: https://masstourists.com

# Contact
twitter:
github:  masstourists
facebook:
email: turism4masses@gmail.com
github_username: masstourists
facebook_username:
twitter_username:

# SEO
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/img/seo/masstourists-opg-facebook.png"

# Favicon
touch_icon: "https://masstourists.com/assets/img/logo/apple-touch-icon-144-precomposed.png"
favicon: "https://masstourists.com/assets/img/logo/favicon.ico"

# Build settings
markdown: kramdown
highlighter: rouge

#

sass:
  sass_dir: _sass
  style: compression

collections:
  activities:
    output: true
  services:
    output: true



plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
